# Generated by Django 5.0.1 on 2024-01-27 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=3)),
                ('contract_number', models.CharField(max_length=10)),
                ('vendor_code', models.CharField(max_length=6)),
                ('vendor_name', models.CharField(max_length=255)),
                ('certificate_number', models.CharField(max_length=10)),
                ('certificate_date', models.DateField()),
                ('certificate_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tds_section_code', models.CharField(max_length=4)),
                ('tax_order_section', models.CharField(max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('consumed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tax_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxorders.taxorder')),
            ],
        ),
    ]
