# Generated by Django 5.0.1 on 2024-01-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateconsumption',
            name='document_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
