# Generated by Django 5.0.1 on 2024-01-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxorders', '0002_certificateconsumption_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateconsumption',
            name='document_number',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='taxorder',
            name='certificate_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
