# Generated by Django 5.0.1 on 2024-01-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxorders', '0003_alter_certificateconsumption_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxorder',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='taxorder',
            name='consumed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
