# Generated by Django 5.0.1 on 2024-01-31 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxorders', '0006_taxorder_fiscalyear_taxorder_sectioncode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ola_number', models.IntegerField(default=0, max_length=10)),
                ('vendor_code', models.IntegerField(default=0, max_length=6)),
                ('vendor_name', models.CharField(max_length=255)),
                ('payment_currency', models.CharField(choices=[('USD', 'USD'), ('JPY', 'JPY'), ('EUR', 'EUR'), ('AED', 'AED')], max_length=3)),
                ('payment_bank', models.CharField(max_length=255)),
                ('payment_swift', models.CharField(max_length=255)),
                ('payment_inter', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('payment_iban', models.CharField(max_length=255)),
                ('payment_ibank', models.CharField(max_length=255)),
                ('payment_iswift', models.CharField(max_length=255)),
                ('payment_iiban', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
