# Generated by Django 5.0.1 on 2024-01-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxorders', '0007_contractmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmaster',
            name='vendor_address',
            field=models.CharField(default='address', max_length=255),
        ),
    ]
